[versions]
shadow = "8.3.6"
runPaper = "2.3.1"

paper = "1.21.10-R0.1-SNAPSHOT"

placeholderapi = "2.11.6"
packetevents = "2.10.1"
tab = "5.3.2"
skinsrestorer = "15.9.0"
caffeine = "3.2.0"
entitylib = "2.4.11"
bstats = "3.1.0"
supervanish = "6.2.18-3"

junit-jupiter = "5.13.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
tab = { module = "com.github.NEZNAMY:TAB-API", version.ref = "tab" }
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
entitylib = { module = "com.github.Tofaa2.EntityLib:spigot", version.ref = "entitylib" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
supervanish = { module = "com.github.LeonMangler:SuperVanish", version.ref = "supervanish" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
